Make Relationship Status Dependent On Dates
shahrukh-compucorp/civicrm-core pull request #1
Opened 2020-10-16 09:21 UTC by shahrukh-compucorp

## Overview
This pr changes relationship saving logic in a way that relationship will only be valid if it has valid dates otherwise it will be disabled. This pr also renames and extends disable_expired_relationships job. Now this job also looks for relationships whose start date matches today's date but it is disabled and changes the status for these relationships to active. 

## Before
Previously no matter what dates has been selected a relationship was always marked as active when it was being created.

## Technical Details
- This pr changes the create function in Relationship Bao file to set the relationship as disabled if it does not have valid dates. 
- This pr also changes `civicrm_api3_job_disable_expired_relationships` function which was executed by disable expired relationship job.
- This pr also adds upgraders to rename the disable expired relationship job to `Enable disable relationships`.

2020-10-16 11:13 UTC, tunbola requested changes

2020-10-16 11:13 UTC, tunbola commented on api/v3/Job.php
> +  $result = CRM_Contact_BAO_Relationship::enableDisableAllRelationships();
Based on my previous comment, I still feel `toggleRelationshipStatus` is a better name for this: 
Toggling means to switch something on and off. In this case it is either setting the status to 0 or 1 based on some conditions so it is toggling

You can leave as is and see what core feels about the name.

2020-10-16 11:13 UTC, tunbola commented on CRM/Contact/BAO/Relationship.php
> +              OR (is_active = 1 AND end_date < CURDATE())";
Should be `WHERE (is_active = 0 AND start_date <= CURDATE())`

Re your previous response on this:

What if the cron fails to run today for some reasons and runs the next day after and we now have a relationship with start date that is yesterday and will be inactive forever?

2020-10-16 11:13 UTC, tunbola commented on tests/phpunit/api/v3/JobTest.php
> +    $this->callAPISuccess($this->_entity, 'enable_disable_relationships', []);
Why can't we have another test for the `testCallEnableDisableRelationships` functionality ? There are at least two scenarios to test.

(1) Test that the status will be set to disabled when end date is in past
(2) Test that previously inactive relationship will be set active if start date equals today.
(3) Test that relationship status is not modified when it does not belong to any of the criteria.

2020-10-16 11:13 UTC, tunbola commented on tests/phpunit/api/v3/RelationshipTest.php
> +  public function testEnableDisableAllRelationships() {
I fell that basically, renaming the function to `EnableDisableAllRelationships` means it now does two things. It can turn a relationship status on and off. Before it only turns it off. Now that it turns it off, we should have at least one test for each scenario.

2020-10-16 11:16 UTC, tunbola commented
@shahrukh-compucorp Quick notes:

Please make sure to preceed the PR title with the issue number and also same thing with commit messages. Check this PR as a ref: https://github.com/civicrm/civicrm-core/pull/18783

Also if you can break the commits up a bit will be nice and easier to review.  e.g
A commit for modifying API and BAO file
A commit for adding upgrader and modifying for new installation
A commit for unit tests.

2020-10-18 09:26 UTC, shahrukh-compucorp commented on api/v3/Job.php
> +  $result = CRM_Contact_BAO_Relationship::enableDisableAllRelationships();
No its not necessarily a toggle it might be possible that it will do nothing to a relationship. Toggling would be like if all 1s are converted to zero and all zeros are converted to 1s but again yeah that is my personal feelings and you might be right about it so yeah lets see if core also wants to change the name then we will have no option.

2020-10-18 09:33 UTC, shahrukh-compucorp commented on CRM/Contact/BAO/Relationship.php
> +              OR (is_active = 1 AND end_date < CURDATE())";
modified the condition based on your comments to pickup all the relationship that have start date of earlier or today and end date is null or greater or equal to today

2020-10-19 11:22 UTC, tunbola requested changes
@shahrukh-compucorp , One of your commit messages says `Make is_valid field dependent on dates for relationship…` What field is this `is_valid` ?

Also don't forget to prefix PR title with issue number.

2020-10-19 11:22 UTC, tunbola commented on tests/phpunit/api/v3/JobTest.php
> +              VALUES ($relationshipTypeID, $individualID, $orgID, 0, '$yesterday')";
Why are we using an SQL query when the API is available? The test you modified above uses the API to create a relationship, any reason why you are not using the API?

2020-10-19 11:22 UTC, tunbola commented on tests/phpunit/api/v3/RelationshipTest.php
> +    $query = "INSERT INTO civicrm_relationship
Why are we not using the API here?

2020-10-19 11:32 UTC, shahrukh-compucorp commented on tests/phpunit/api/v3/JobTest.php
> +              VALUES ($relationshipTypeID, $individualID, $orgID, 0, '$yesterday')";
I f I will use api then I wont be able to create a relationship with valid dates and is_active as 0 because while saving it will turn the is_active to 1 as dates will be valid

2020-10-19 11:32 UTC, shahrukh-compucorp commented on tests/phpunit/api/v3/RelationshipTest.php
> +    $query = "INSERT INTO civicrm_relationship
same thing goes for this as well

2020-10-19 13:02 UTC, tunbola approved these changes

2020-10-19 14:27 UTC, merged